---
kind: pipeline
type: docker
name: Use Sonarqube
steps:
- name: Analyze code project
  image: sijaymm/sonar-msbuild:latest
  commands:
     - dotnet /sonar-scanner/SonarScanner.MSBuild.dll begin /k:DotNetCore-Web-App-POC /o:"cjmanaguelod1895" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login="7053feaa49bfd77702a73e9bda280f5e9c16a6bd" /d:sonar.verbose=true
     - dotnet build
     - dotnet /sonar-scanner/SonarScanner.MSBuild.dll end /d:sonar.login="7053feaa49bfd77702a73e9bda280f5e9c16a6bd"
  
trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
